[theme]
base = "dark"
primaryColor = "#2693FF"
backgroundColor = "#080F18"
secondaryBackgroundColor = "#18253A"
textColor = "#F4F7FB"

[theme.sidebar]
backgroundColor = "#07182C"
secondaryBackgroundColor = "#11243E"
primaryColor = "#2693FF"
textColor = "#F4F7FB"
